_wandb:
    value:
        cli_version: 0.21.0
        e:
            tqsed8wll8zcldefu8gof3ldwer4dnp1:
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 12
                cpu_count_logical: 24
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "1999701749760"
                        used: "927408869376"
                email: nagtamaghna@gmail.com
                executable: c:\Python313\python.exe
                git:
                    commit: 3e837ec71ad021e29a3eeb2c3af791338e20f400
                    remote: https://github.com/Tamaghnatech/CO2Emissions.git
                gpu: NVIDIA GeForce RTX 4060 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 4352
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Ti
                      uuid: GPU-d1a48f26-44f9-1b15-c7a1-a7b4b567ef87
                host: Tamaghna
                memory:
                    total: "34278547456"
                os: Windows-10-10.0.19045-SP0
                program: c:\Users\Tamaghna\Documents\CO2EmissionsRegression\main.py
                python: CPython 3.13.1
                root: c:\Users\Tamaghna\Documents\CO2EmissionsRegression
                startedAt: "2025-07-18T22:39:54.380276Z"
                writerId: tqsed8wll8zcldefu8gof3ldwer4dnp1
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 5
                - 53
                - 105
            "2":
                - 5
                - 53
                - 105
            "3":
                - 2
                - 13
            "4": 3.13.1
            "5": 0.21.0
            "8":
                - 1
                - 3
            "12": 0.21.0
            "13": windows-amd64
